export const GET_HOME_SCREEN_DATA_START = "GET_HOME_SCREEN_DATA_START";
export const GET_HOME_SCREEN_DATA_SUCCESS = "GET_HOME_SCREEN_DATA_SUCCESS";
export const GET_HOME_SCREEN_DATA_ERROR = "GET_HOME_SCREEN_DATA_ERROR";

