 
export const GET_PRODUCTS_DATA_START = "GET_PRODUCTS_DATA_START";
export const GET_PRODUCTS_DATA_SUCCESS = "GET_PRODUCTS_DATA_SUCCESS";
export const GET_PRODUCTS_DATA_ERROR = "GET_PRODUCTS_DATA_ERROR";


 
export const GET_PRODUCT_DATA_START = "GET_PRODUCT_DATA_START";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_ERROR = "GET_PRODUCT_DATA_ERROR";



export const ADD_PRODUCT_DATA_START = "ADD_PRODUCT_DATA_START";
export const ADD_PRODUCT_DATA_SUCCESS = "ADD_PRODUCT_DATA_SUCCESS";
export const ADD_PRODUCT_DATA_ERROR = "ADD_PRODUCT_DATA_ERROR";



export const UPDATE_PRODUCT_DATA_START = "UPDATE_PRODUCT_DATA_START";
export const UPDATE_PRODUCT_DATA_SUCCESS = "UPDATE_PRODUCT_DATA_SUCCESS";
export const UPDATE_PRODUCT_DATA_ERROR = "UPDATE_PRODUCT_DATA_ERROR";



export const DELETE_PRODUCT_DATA_START = "DELETE_PRODUCT_DATA_START";
export const DELETE_PRODUCT_DATA_SUCCESS = "DELETE_PRODUCT_DATA_SUCCESS";
export const DELETE_PRODUCT_DATA_ERROR = "DELETE_PRODUCT_DATA_ERROR";


