 
export const GET_PRODUCTS_DATA_START = "GET_PRODUCTS_DATA_START";
export const GET_PRODUCTS_DATA_SUCCESS = "GET_PRODUCTS_DATA_SUCCESS";
export const GET_PRODUCTS_DATA_ERROR = "GET_PRODUCTS_DATA_ERROR";


 
export const GET_PRODUCT_DATA_START = "GET_PRODUCT_DATA_START";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_ERROR = "GET_PRODUCT_DATA_ERROR";